'use client'

import { useState, useEffect } from 'react'
import { toast } from 'sonner'
import { Printer } from 'lucide-react'
import type { HallSaleData } from '../types'

const PAYMENT_LABELS: Record<string, string> = {
  cash: 'Cash',
  card: 'Card',
  split: 'Split',
  bank_transfer: 'Bank Transfer',
  instapay: 'InstaPay',
  wallet: 'Wallet',
}

export default function HallSaleTab({ shiftId }: { shiftId: string }) {
  const [data, setData] = useState<HallSaleData | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    fetch(`/api/admin/pos/shifts/hall-sale?shiftId=${shiftId}`)
      .then((res) => res.json())
      .then((result) => setData(result))
      .catch(() => toast.error('Failed to load hall sale data'))
      .finally(() => setLoading(false))
  }, [shiftId])

  if (loading) {
    return <div className="flex items-center justify-center flex-1 text-sm text-white/50">Loading...</div>
  }

  if (!data) {
    return <div className="flex items-center justify-center flex-1 text-sm text-white/50">No data available</div>
  }
  const d = data

  const incomeMethods = Object.entries(d.incomeByMethod).filter(([, v]) => v > 0)
  const refundMethods = Object.entries(d.refundsByMethod || {}).filter(([, v]) => v > 0)
  const expenseMethods = Object.entries(d.expensesByMethod).filter(([, v]) => v > 0)

  function handlePrint() {
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(`
      <html><head><title>Hall Sale - ${new Date(d.shift.startedAt).toLocaleDateString()}</title>
      <style>
        body { font-family: monospace; font-size: 12px; padding: 20px; }
        h1 { font-size: 16px; margin-bottom: 5px; }
        h2 { font-size: 14px; margin: 15px 0 5px; border-bottom: 1px solid #ccc; padding-bottom: 3px; }
        table { width: 100%; border-collapse: collapse; margin: 5px 0; }
        td, th { padding: 3px 8px; text-align: left; }
        th { border-bottom: 1px solid #ccc; }
        .right { text-align: right; }
        .total { font-weight: bold; border-top: 1px solid #999; }
        .diff { color: ${d.difference >= 0 ? 'green' : 'red'}; }
      </style></head><body>
      <h1>Hall Sale Report</h1>
      <p>Date: ${new Date(d.shift.startedAt).toLocaleString()}</p>
      <p>Status: ${d.shift.isOpen ? 'Open' : 'Closed'} | Orders: ${d.shift.orderCount}</p>
      <h2>Income</h2>
      <table>${incomeMethods.map(([m, v]) => `<tr><td>${PAYMENT_LABELS[m] || m}</td><td class="right">E£${v.toFixed(2)}</td></tr>`).join('')}
      <tr class="total"><td>Total Income</td><td class="right">E£${d.totalIncome.toFixed(2)}</td></tr></table>
      ${refundMethods.length > 0 ? `
      <h2>Refunds</h2>
      <table>${refundMethods.map(([m, v]) => `<tr><td>${PAYMENT_LABELS[m] || m}</td><td class="right">-E£${v.toFixed(2)}</td></tr>`).join('')}
      <tr class="total"><td>Total Refunds</td><td class="right">-E£${d.totalRefunds.toFixed(2)}</td></tr></table>` : ''}
      <h2>Expenses</h2>
      <table>${expenseMethods.length > 0 ? expenseMethods.map(([m, v]) => `<tr><td>${PAYMENT_LABELS[m] || m}</td><td class="right">-E£${v.toFixed(2)}</td></tr>`).join('') : '<tr><td>No expenses</td><td class="right">E£0.00</td></tr>'}
      <tr class="total"><td>Total Expenses</td><td class="right">-E£${d.totalExpenses.toFixed(2)}</td></tr></table>
      <h2>Cash Position</h2>
      <table>
       <tr><td>Starting Cash</td><td class="right">E£${d.shift.startingCash.toFixed(2)}</td></tr>
       <tr><td>Cash Income</td><td class="right">E£${(d.incomeByMethod.cash || 0).toFixed(2)}</td></tr>
       ${(d.refundsByMethod?.cash || 0) > 0 ? `<tr><td>Cash Refunds</td><td class="right">-E£${(d.refundsByMethod.cash || 0).toFixed(2)}</td></tr>` : ''}
       <tr><td>Cash Expenses</td><td class="right">-E£${(d.expensesByMethod.cash || 0).toFixed(2)}</td></tr>
       <tr class="total"><td>Expected Cash</td><td class="right">E£${d.expectedCash.toFixed(2)}</td></tr>
      <tr><td>Actual Ending Cash</td><td class="right">E£${d.actualEndingCash.toFixed(2)}</td></tr>
      <tr class="total"><td>Difference</td><td class="right ${d.difference >= 0 ? '' : ''}">E£${d.difference.toFixed(2)}</td></tr>
      </table>
      <p style="margin-top: 20px; font-size: 10px; color: #999;">Generated by Gümüş Güneş POS</p>
      </body></html>
    `)
    w.document.close()
    w.print()
  }

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between mb-4 pb-3 border-b border-white/10">
        <div>
          <h2 className="font-display text-lg font-semibold text-silver-soft">Hall Sale</h2>
          <p className="text-xs text-white/40">
            {new Date(d.shift.startedAt).toLocaleString()}
            {d.shift.closedAt && ` — ${new Date(d.shift.closedAt).toLocaleString()}`}
            <span className={`ml-2 px-1.5 py-0.5 rounded text-xs font-medium ${d.shift.isOpen ? 'bg-emerald-500/10 text-emerald-400' : 'bg-white/5 text-white/40'}`}>
              {d.shift.isOpen ? 'Open' : 'Closed'}
            </span>
          </p>
        </div>
        <button onClick={handlePrint} className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-silver-soft hover:bg-gold/10 hover:text-gold rounded-lg transition-all border border-white/10">
          <Printer className="h-4 w-4" /> Print
        </button>
      </div>

      <div className="flex-1 overflow-y-auto space-y-5 scroll-luxury">
        <div className="grid grid-cols-3 gap-3">
          <div className="pos-glass rounded-xl p-4 text-center">
            <p className="text-xs text-white/40 uppercase tracking-wide mb-1">Total Income</p>
            <p className="text-2xl font-bold text-emerald-400">E£{d.totalIncome.toFixed(2)}</p>
          </div>
          <div className="pos-glass rounded-xl p-4 text-center">
            <p className="text-xs text-white/40 uppercase tracking-wide mb-1">Total Expenses</p>
            <p className="text-2xl font-bold text-red-400">-E£{d.totalExpenses.toFixed(2)}</p>
          </div>
          <div className="pos-glass rounded-xl p-4 text-center">
            <p className="text-xs text-white/40 uppercase tracking-wide mb-1">Net</p>
            <p className={`text-2xl font-bold ${d.netTotal >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
              E£{d.netTotal.toFixed(2)}
            </p>
          </div>
        </div>

        <div className="pos-glass rounded-xl p-4">
          <h3 className="text-sm font-semibold text-silver-soft mb-3">Income Breakdown</h3>
          {incomeMethods.length > 0 ? (
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10 text-left text-white/40">
                  <th className="pb-2 font-medium">Method</th>
                  <th className="pb-2 font-medium text-right">Amount</th>
                </tr>
              </thead>
              <tbody>
                {incomeMethods.map(([method, amount]) => (
                  <tr key={method} className="border-b border-white/5">
                    <td className="py-2 text-silver-soft font-medium">{PAYMENT_LABELS[method] || method}</td>
                    <td className="py-2 text-right text-emerald-400 font-medium">E£{amount.toFixed(2)}</td>
                  </tr>
                ))}
                <tr className="font-bold">
                  <td className="py-2 text-silver-soft">Total</td>
                  <td className="py-2 text-right text-emerald-400">E£{d.totalIncome.toFixed(2)}</td>
                </tr>
              </tbody>
            </table>
          ) : (
            <p className="text-sm text-white/40">No income recorded</p>
          )}
        </div>

        {refundMethods.length > 0 && (
          <div className="pos-glass rounded-xl p-4">
            <h3 className="text-sm font-semibold text-silver-soft mb-3">Refunds</h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10 text-left text-white/40">
                  <th className="pb-2 font-medium">Method</th>
                  <th className="pb-2 font-medium text-right">Amount</th>
                </tr>
              </thead>
              <tbody>
                {refundMethods.map(([method, amount]) => (
                  <tr key={method} className="border-b border-white/5">
                    <td className="py-2 text-silver-soft font-medium">{PAYMENT_LABELS[method] || method}</td>
                    <td className="py-2 text-right text-red-400 font-medium">-E£{amount.toFixed(2)}</td>
                  </tr>
                ))}
                <tr className="font-bold">
                  <td className="py-2 text-silver-soft">Total Refunds</td>
                  <td className="py-2 text-right text-red-400">-E£{d.totalRefunds.toFixed(2)}</td>
                </tr>
              </tbody>
            </table>
          </div>
        )}

        <div className="pos-glass rounded-xl p-4">
          <h3 className="text-sm font-semibold text-silver-soft mb-3">Expenses Breakdown</h3>
          {expenseMethods.length > 0 ? (
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10 text-left text-white/40">
                  <th className="pb-2 font-medium">Method</th>
                  <th className="pb-2 font-medium text-right">Amount</th>
                </tr>
              </thead>
              <tbody>
                {expenseMethods.map(([method, amount]) => (
                  <tr key={method} className="border-b border-white/5">
                    <td className="py-2 text-silver-soft font-medium">{PAYMENT_LABELS[method] || method}</td>
                    <td className="py-2 text-right text-red-400 font-medium">-E£{amount.toFixed(2)}</td>
                  </tr>
                ))}
                <tr className="font-bold">
                  <td className="py-2 text-silver-soft">Total</td>
                  <td className="py-2 text-right text-red-400">-E£{d.totalExpenses.toFixed(2)}</td>
                </tr>
              </tbody>
            </table>
          ) : (
            <p className="text-sm text-white/40">No expenses recorded</p>
          )}
        </div>

        <div className="pos-glass-strong rounded-xl p-4">
          <h3 className="text-sm font-semibold text-silver-soft mb-3">Cash Position</h3>
          <table className="w-full text-sm">
            <tbody>
              <tr className="border-b border-white/10">
                <td className="py-2 text-white/50">Starting Cash</td>
                <td className="py-2 text-right font-medium text-silver-soft">E£{d.shift.startingCash.toFixed(2)}</td>
              </tr>
              <tr className="border-b border-white/10">
                <td className="py-2 text-white/50">+ Cash Income</td>
                <td className="py-2 text-right font-medium text-emerald-400">+E£{(d.incomeByMethod.cash || 0).toFixed(2)}</td>
              </tr>
              {(d.refundsByMethod?.cash || 0) > 0 && (
                <tr className="border-b border-white/10">
                  <td className="py-2 text-white/50">- Cash Refunds</td>
                  <td className="py-2 text-right font-medium text-red-400">-E£{(d.refundsByMethod.cash || 0).toFixed(2)}</td>
                </tr>
              )}
              <tr className="border-b border-white/10">
                <td className="py-2 text-white/50">- Cash Expenses</td>
                <td className="py-2 text-right font-medium text-red-400">-E£{(d.expensesByMethod.cash || 0).toFixed(2)}</td>
              </tr>
              <tr className="border-b border-white/10 font-bold">
                <td className="py-2 text-silver-soft">Expected Cash</td>
                <td className="py-2 text-right text-gold">E£{d.expectedCash.toFixed(2)}</td>
              </tr>
              <tr className="border-b border-white/10">
                <td className="py-2 text-white/50">Actual Ending Cash</td>
                <td className="py-2 text-right font-medium text-silver-soft">E£{d.actualEndingCash.toFixed(2)}</td>
              </tr>
              <tr className="font-bold">
                <td className="py-2 text-silver-soft">Difference</td>
                <td className={`py-2 text-right ${d.difference >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                  E£{d.difference >= 0 ? '+' : ''}{d.difference.toFixed(2)}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
