import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import path from 'path'
import fs from 'fs'
import { generateStorefront } from '@/lib/engine/generator'

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const store = await prisma.store.findUnique({ where: { id: params.id } })
  if (!store) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const features = JSON.parse(store.features || '[]')
  const slug = store.slug

  // The generated store goes to a dedicated output
  const outputDir = path.resolve(process.cwd(), 'generated', slug)

  // Resolve main site source (parent directory of store-builder)
  const sourceDir = path.resolve(process.cwd(), '..')

  try {
    await generateStorefront({
      sourceDir,
      outputDir,
      enabledFeatures: features,
      theme: {
        primaryColor: store.primaryColor,
        secondaryColor: store.secondaryColor,
        accentColor: store.accentColor,
        borderRadius: store.borderRadius,
        fontFamily: store.fontFamily,
        logoUrl: store.logoUrl || undefined,
        layoutType: (store as any).layoutType as 'single-page' | 'multi-page' | undefined,
      },
      demo: {
        enabled: store.isDemo,
        storeName: store.name,
        expiresAt: store.demoExpiresAt?.toISOString(),
      },
      storeName: store.name,
      storeSlug: slug,
      layoutType: (store as any).layoutType as 'single-page' | 'multi-page' | undefined,
    })

    // Generate a standalone Prisma schema for the generated store
    generateStandaloneSchema(outputDir, features)

    // Update store status
    await prisma.store.update({
      where: { id: params.id },
      data: {
        lastGeneratedAt: new Date(),
        generatedPath: outputDir,
        status: store.isDemo ? 'demo' : 'active',
      },
    })

    // Create deployment record
    const deployment = await prisma.deployment.create({
      data: {
        storeId: store.id,
        version: '1.0.0',
        mode: store.isDemo ? 'demo' : 'production',
        status: 'ready',
        outputPath: outputDir,
      },
    })

    return NextResponse.json({
      ok: true,
      outputPath: outputDir,
      deployment,
      message: `Storefront generated at ${outputDir}`,
    })
  } catch (err: any) {
    console.error('Generation failed:', err)
    return NextResponse.json({ ok: false, error: err.message }, { status: 500 })
  }
}

/**
 * Generate a standalone Prisma schema for the generated store,
 * including only models for enabled features.
 */
function generateStandaloneSchema(outputDir: string, features: string[]) {
  const mainSchemaPath = path.resolve(process.cwd(), '..', 'prisma', 'schema.prisma')
  if (!fs.existsSync(mainSchemaPath)) {
    console.warn('Main schema not found, skipping standalone schema generation')
    return
  }

  let schema = `// Generated schema for ${path.basename(outputDir)}
// Auto-generated by Store Builder — do not edit directly

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`

  const mainContent = fs.readFileSync(mainSchemaPath, 'utf-8')

  // Parse model blocks
  const modelRegex = /^model\s+(\w+)\s*\{[\s\S]*?^}/gm
  const enumRegex = /^enum\s+(\w+)\s*\{[\s\S]*?^}/gm

  // Feature-to-model mapping
  const featureModels: Record<string, string[]> = {
    storefront: ['Store', 'Product', 'Category', 'Brand', 'ProductRelation', 'ProductEmbedding', 'Review'],
    cart: ['WishlistItem'],
    checkout: ['Order', 'OrderItem', 'Discount', 'Governorate', 'ShippingMethod', 'ShippingRate', 'ShippingRule', 'Shipment', 'OtpVerification'],
    wishlist: ['WishlistItem'],
    reviews: ['Review'],
    blog: ['BlogPost'],
    faq: ['FaqEntry'],
    banners: ['Banner'],
    staticPages: ['StaticPage'],
    newsletter: ['Newsletter'],
    discounts: ['Discount'],
    giftCards: ['GiftCard'],
    basicAccounting: ['Expense'],
    doubleEntry: ['Account', 'JournalEntry', 'JournalLine'],
    financialReports: ['Account', 'JournalEntry', 'JournalLine'],
    bankReconciliation: ['BankAccount', 'BankTransaction', 'JournalEntry'],
    payroll: ['PayrollRun', 'PayrollItem', 'Employee'],
    invoicing: ['Invoice', 'InvoiceItem'],
    bills: ['Bill', 'BillItem'],
    adminDashboard: ['Admin', 'Role', 'ActivityLog'],
    productManagement: ['Product', 'Brand', 'Category'],
    orderManagement: ['Order', 'OrderItem', 'Return', 'ReturnItem', 'Shipment'],
    customerManagement: ['User', 'Address', 'SavedCard', 'CustomerNote', 'CustomerActivityLog', 'CustomerSegment', 'LoyaltyTier'],
    pos: ['Shift', 'Branch', 'BranchStock'],
    inventory: ['Warehouse', 'StockLevel', 'StockTransfer', 'InventoryLog', 'BranchStock', 'PurchaseOrder', 'PurchaseOrderItem'],
    shipping: ['ShippingMethod', 'ShippingRate', 'ShippingRule', 'Shipment', 'Governorate'],
    analytics: ['ScheduledReport'],
    roleManagement: ['Role', 'Admin'],
    multiBranch: ['Branch', 'BranchStock', 'Shift'],
    chat: ['Conversation', 'Message'],
    webhooks: ['Webhook', 'WebhookDelivery'],
    apiKeys: ['ApiKey'],
    auditLogs: ['ActivityLog'],
    seo: ['SiteSetting'],
    backInStock: ['BackInStock'],
    saleCampaigns: ['SaleCampaign'],
    emailCampaigns: ['EmailCampaign'],
    pushCampaigns: ['PushCampaign'],
    abandonedCart: ['AbandonedCart'],
    referrals: ['Referral', 'ReferralConfig'],
    socialMedia: ['SocialAccount', 'SocialPost', 'SocialDraft', 'SocialCampaign'],
    userAccounts: ['User', 'Address', 'SavedCard', 'ResetToken'],
    multiCurrency: ['Currency'],
    multiLanguage: ['Translation'],
    featureFlags: ['FeatureFlag'],
    returnRequests: ['ReturnRequest', 'ReturnItem', 'Return'],
  }

  // Collect required model names
  const requiredModels = new Set<string>()
  requiredModels.add('Store') // Always include the Store model
  for (const feat of features) {
    const models = featureModels[feat]
    if (models) models.forEach(m => requiredModels.add(m))
  }

  // Collect referenced models recursively
  const collected = new Set<string>()
  function collectModels(names: string[]) {
    for (const name of names) {
      if (collected.has(name)) continue
      collected.add(name)
      // Find the model block and extract referenced models
      const match = mainContent.match(new RegExp(`^model\\s+${name}\\s*\\{[\\s\\S]*?^}`, 'm'))
      if (match) {
        const refs = match[0].match(/(\w+)(?:\s+\w+)?\s+(@relation|\[\])/g)
        if (refs) {
          const refModels = refs.map(r => r.split(/\s+/)[0]).filter(r => r !== name && !['String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json'].includes(r))
          collectModels(refModels)
        }
        // Add referenced through-model enums
        const enumRefs = match[0].match(/(\w+)(?=\s*\?|\s*$)/g)
        if (enumRefs) {
          const enumsToCheck = enumRefs.filter(r => r[0] === r[0].toUpperCase() && !['String', 'Int', 'Float', 'Boolean', 'DateTime', 'Json', 'Id', 'Null'].includes(r))
          enumsToCheck.forEach(e => {
            if (mainContent.includes(`enum ${e} {`)) collected.add(e)
          })
        }
      }
    }
  }

  collectModels([...requiredModels])

  // Extract all needed model and enum blocks
  const allEnums = [...mainContent.matchAll(enumRegex)].map(m => m[0])
  const allModels = [...mainContent.matchAll(modelRegex)].map(m => m[0])

  // Collect enums that are referenced by collected models
  for (const modelBlock of allModels) {
    const nameMatch = modelBlock.match(/^model\s+(\w+)/)
    if (nameMatch && collected.has(nameMatch[1])) {
      const enumRefs = modelBlock.match(/\b([A-Z][A-Z_]+)\b/g) || []
      enumRefs.forEach(e => {
        if (mainContent.includes(`enum ${e} {`)) collected.add(e)
      })
    }
  }

  // Add enums that are referenced
  for (const enumBlock of allEnums) {
    const nameMatch = enumBlock.match(/^enum\s+(\w+)/)
    if (nameMatch && collected.has(nameMatch[1])) {
      schema += enumBlock + '\n\n'
    }
  }

  // Add models
  for (const modelBlock of allModels) {
    const nameMatch = modelBlock.match(/^model\s+(\w+)/)
    if (nameMatch && collected.has(nameMatch[1])) {
      // Deep-copy the Store model but remove the multi-tenant relations
      let cleaned = modelBlock
      if (nameMatch[1] === 'Store') {
        // Keep Store minimal — it's the tenant root
      }
      schema += cleaned + '\n\n'
    }
  }

  // Write to generated project's prisma directory
  const prismaDir = path.join(outputDir, 'prisma')
  fs.mkdirSync(prismaDir, { recursive: true })
  fs.writeFileSync(path.join(prismaDir, 'schema.prisma'), schema, 'utf-8')

  // Write a .env template for the generated project
  const envTemplate = `# Database connection for ${path.basename(outputDir)}
# Replace with your PostgreSQL connection string
DATABASE_URL="postgresql://user:password@localhost:5432/${path.basename(outputDir)}"

# Store configuration
NEXT_PUBLIC_STORE_NAME="${path.basename(outputDir)}"
`
  fs.writeFileSync(path.join(outputDir, '.env.example'), envTemplate, 'utf-8')

  console.log(`   Standalone schema written to prisma/schema.prisma (${[...collected].length} models)`)
}