'use client'

import { usePosStore } from '../stores/posStore'

export function usePos() {
  const store = usePosStore()

  return {
    search: store.search,
    setSearch: store.setSearch,
    products: store.products,
    totalProducts: store.totalProducts,
    currentPage: store.currentPage,
    totalPages: store.totalPages,
    isLoadingProducts: store.isLoadingProducts,
    setProductPage: store.setProductPage,
    setLoadingProducts: store.setLoadingProducts,
    cart: store.cart,
    addToCart: store.addToCart,
    updateQuantity: store.updateQuantity,
    removeFromCart: store.removeFromCart,
    discountCode: store.discountCode,
    setDiscountCode: store.setDiscountCode,
    appliedDiscount: store.appliedDiscount,
    setAppliedDiscount: store.setAppliedDiscount,
    checkoutLoading: store.checkoutLoading,
    setCheckoutLoading: store.setCheckoutLoading,
    paymentMethod: store.paymentMethod,
    setPaymentMethod: store.setPaymentMethod,
    cashAmount: store.cashAmount,
    cardAmount: store.cardAmount,
    handleCashChange: store.handleCashChange,
    handleCardChange: store.handleCardChange,
    receipt: store.receipt,
    setReceipt: store.setReceipt,
    subtotal: store.subtotal(),
    discountAmount: store.discountAmount(),
    total: store.total(),
    itemDiscountTotal: store.itemDiscountTotal(),
    taxAmount: store.taxAmount(),
    taxRate: store.taxRate,
    setTaxRate: store.setTaxRate,
    parsedCash: store.parsedCash(),
    parsedCard: store.parsedCard(),
    change: store.change(),
    newSale: store.newSale,
    setItemDiscount: store.setItemDiscount,
    heldOrders: store.heldOrders,
    holdOrder: store.holdOrder,
    recallOrder: store.recallOrder,
    removeHeldOrder: store.removeHeldOrder,
    customer: store.customer,
    setCustomer: store.setCustomer,
    customerSearch: store.customerSearch,
    setCustomerSearch: store.setCustomerSearch,
    orderNotes: store.orderNotes,
    setOrderNotes: store.setOrderNotes,
  }
}
